baseurl = "https://va2577.github.io/"
languageCode = "ja-jp"
title = "Espresso & Onigiri"

defaultContentLanguage = "ja"
#disqusShortname = "qh7463"
#googleAnalytics = "UA-72506171-1"
hasCJKLanguage = true
paginate = 20
sectionPagesMenu = "main"
theme = "an6474"
copyright = "&copy; 2015 Espresso & Onigiri"

[params]
  github = "va2577"
#  twitter = "@rv1471"
  [params.adsense]
    client = "ca-pub-9305907051774965"
    slot = "2028899530"
