baseurl = "https://va2577.github.io/"
languageCode = "ja-jp"
title = "Espresso & Onigiri"

defaultContentLanguage = "ja"
# disqusShortname = "qh7463"
# googleAnalytics = "UA-72506171-1"
hasCJKLanguage = true
paginate = 20
sectionPagesMenu = "main"
theme = "theme2"
copyright = "&copy; 2015 Espresso & Onigiri"

[params]
  github = "va2577"
  twitter = "@rv1471"
