baseurl = "https://va2577.github.io/"
languageCode = "ja-jp"
title = "Espresso & Onigiri"

defaultContentLanguage = "ja"
#disqusShortname = "qh7463"
#googleAnalytics = "UA-72506171-1"
hasCJKLanguage = true
paginate = 40
sectionPagesMenu = "main"
theme = "hugo-swift-theme"
copyright = "&copy; 2015 Espresso & Onigiri"
canonifyurls = true

# Enable syntax highlighting
# comment on delete the following lines 11 ~ 13
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "friendly"

[params]
  github = "va2577"
#  twitter = "@rv1471"
  image = "logo.png"
  logo = "logo.png"
  [params.adsense]
    client = "ca-pub-9305907051774965"
    slot = "2028899530"
